version: '3.7'

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
volumes:
  db_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local